---
# Description : configure docker registry ids
# file : _set_docker_registry.yml
# source : https://docs.ansible.com/ansible/latest/collections/community/docker/docker_login_module.html
# from : https://github.com/nickjj/ansible-docker/blob/master/tasks/main.yml

- name: Restart Docker now to make sure `docker login` works
  ansible.builtin.meta: "flush_handlers"

- name: Manage Docker registry login credentials
  community.docker.docker_login:
    registry_url: "{{ item.registry_url | d(omit) }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email | d(omit) }}"
    reauthorize: "{{ item.reauthorize | d(omit) }}"
    config_path: "{{ item.config_path | d(omit) }}"
    state: "{{ item.state | d('present') }}"
  loop: "{{ docker_registries }}"
  loop_control:
    label: '{{ {"registry_url": item.registry_url | d("https://index.docker.io/v1/"), "username": item.username, "state": item.state | d("present")} }}'  # yamllint disable-line rule:line-length
  when: item.username is defined and item.password is defined